### ISSUE TITLE
代码赏心悦目，一键运行，不愧是nipsspotlight

### ISSUE THREAD

**Issue by NKUShaw** [K1nght/Unified-Unlearning-w-Remain-Geometry#1]

**Comment by NKUShaw** [comment]
但是我并没有unlearn出效果，反而精度有所上升，请问我可以调整哪些超参数来控制unlearn的效果？

**Comment by K1nght** [comment]
Thank you so much for your interest and appreciation of our work. I think you might have come across this confusion when carrying out the **classification** task. When the effect of unlearning is not significant, I suggest increasing the "forget_alpha" on line 111 or reducing the "forget_freq" on line 109 in `Classification/unlearn/sfron.py` to achieve effective unlearning.
