### ISSUE TITLE
folder structure of SD

### ISSUE THREAD

**Issue by YuanXun2024** [K1nght/Unified-Unlearning-w-Remain-Geometry#2]
Hi,

Thanks for releasing the source code. I have a question about the folder structure of SD.

From my understanding, I should download 'Original Stable Diffusion' first. Then download your 'SD' folder and copy all sub-folders of 'SD' to 'Original Stable Diffusion'. Last, run your Python instructions under the 'Original Stable Diffusion' folder. Please correct me if I am wrong. It would be helpful to give a screenshot of the final project folder.

Thank you.

**Comment by K1nght** [comment]
Hi,

Thank you for raising the confusion regarding the SD pipeline setup. The process you've followed is indeed correct. I have updated the README file to include the folder structure as following for better clarity, which should help verify the correctness of your setup process.

```
SD/
├── config/               # Directory for storing configuration files
├── ldm/                  # Directory for model and data files
├── data/                 # Directory for storing generated images
│   ├── nsfw/             # NSFW images generated from SD
│   └── not-nsfw/         # Non-NSFW images generated from SD
├── fisher/               # Directory for storing fisher and saliency masks
├── models/               # Directory for model checkpoints
│   └── ldm/              # Location for SD-v1-4 weights
├── prompts/              # Directory containing prompt files
│   ├── nsfw.csv
│   ├── not-nsfw.csv
├── eval-scripts/         # Main evaluation scripts location
│   ├── generate-images.py
│   └── nudenet-classes.py
└── train-scripts/        # Main training scripts location
    ├── generate_fisher.py
    ├── generate_fisher_mask.py
    └── nsfw_removal.py
```

Feel free to check the updated README, and let me know if you have any further questions!

**Comment by YuanXun2024** [comment]
Thank you!
