### ISSUE TITLE
Did not found nsfw.csv and not-nsfw.csv

### ISSUE THREAD

**Issue by YuanXun2024** [K1nght/Unified-Unlearning-w-Remain-Geometry#3]
Hi,

To run the instructions under SD. I think we need nsfw.csv and not-nsfw.csv. But I did not find them in the released repo.

Could you please release those files? Thank you.

**Comment by K1nght** [comment]
I have uploaded the example templates for `nsfw.csv` and `not-nsfw.csv` in the SD/prompts folder. Actually, you can also create these files by paraphrasing or adjusting your own data to fit the required format.
